[package]
name = "embazeler"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.6.0", features = ["libuv", "neovim-0-11"] }
tokio = { version = "1.45.1", features = ["full", "sync"] }
